### PR TITLE
Modulesync: use voxpupuli helper gems

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Comment by ekohl** [comment]
It looks like no tests are ran anymore since the default job is no longer defined. This shouldn't have been merged.

**Comment by wbclark** [comment]
> It looks like no tests are ran anymore since the default job is no longer defined. This shouldn't have been merged.

Sorry for the premature approval then, but I see the tests ran here: https://travis-ci.org/github/theforeman/puppet-dhcp/builds/674031954

What information am I missing?

**Comment by wbclark** [comment]
I see it here now, it ran basically an empty set of spec tests: https://travis-ci.org/github/theforeman/puppet-dhcp/jobs/674031955

**Pull request merged**
