### PR TITLE
Fixes #20912 - Listen on interfaces in EL7

### PR DESCRIPTION
**Pull request by ekohl**
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-dhcp-configuring-server.html#starting-stopping-server suggests to override the full file but this just uses a drop-in to change as little as possible.

### CODE REVIEW

**Comment by ekohl** [comment]
Verified with https://github.com/theforeman/puppet-dhcp/pull/111 but maybe I should add some regular spec tests as well.

**Comment by mmoll** [comment]
looking OK, pending tests. 👍

**Comment by ekohl** [comment]
I took the liberty of refactoring the tests as well. For readability it's in a separate commit.

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
