### PR TITLE
Allow turning omapi off

### PR DESCRIPTION
**Pull request by russellshackleford**
Defaults to maintaining existing behaviour. Also cleanly applies to the master branch as of the time of this PR.

### CODE REVIEW

**Comment by domcleal** [comment]
Should this be applied to master and then moved to 3.2-stable (if anybody is willing to maintain that)? It's new functionality.

**Comment by russellshackleford** [comment]
@domcleal, what are your plans for the 2 commits in master? Are they intended for a 4.0 release or a 3.2 release? I can move this commit to whichever branch you wish. I have to also make bootp a boolean as it conflicts with failover so I'd like to know which branch to base it from as well.

**Comment by russellshackleford** [comment]
@domcleal I have made a couple of new branches: bootp-3.1 and bootp-master. Both cherry-pick this commit and adds a nearly identical commit for bootp but one adds it on top of master and the other on top of 3.1-stable. As I don't know which way you want to go on this, I'll hold off making the PR until I hear from you.

**Comment by mmoll** [comment]
Merged into master and into the newly created 3.2-stable branch. I'm unsure how long-lived this 3.2.x series will be and if it will see releases, but at least we do have the possibility now.

@russellshackleford please always open PRs against master.

**Pull request closed without merging**
