### PR TITLE
add support to set search domains in the generated dhcpd configuration file

### PR DESCRIPTION
**Pull request by johnmehringer**
I added support to set the search domains to be added to the dhpcd.conf file since we need it in our foreman environment.

### CODE REVIEW

**Comment by ekohl** [comment]
:+1: looks good. Would you mind squashing all commits?

**Comment by johnmehringer** [comment]
I squashed all of the commits.  Let me know if anything else is needed.  Thanks!

**Comment by ekohl** [comment]
Would you mind rebasing to current master and adding a parameter to the ```full parameters``` tset in ```spec/defines/pool_spec.rb``` so we get some coverage? Other than that I think it's good to go.

**Comment by johnmehringer** [comment]
I added a parameter to the full parameters test.  Let me know if you need anything else changed.  Thanks!

**Comment by mmoll** [comment]
There are still three commits in this PR, please squash these together into one single commit, then force push the result into your master branch (we can also do the squashing before mrerging, if it's too much if a hassle, just tell us in that case).

**Comment by johnmehringer** [comment]
Sorry about that.  I am somewhat new to git. I think it should all be squashed now.

**Comment by mmoll** [comment]
merged, thanks @johnmehringer!

**Pull request closed without merging**
