### PR TITLE
Added UEFI HTTP Boot support

### PR DESCRIPTION
**Pull request by lzap**
This option is needed to allow UEFI HTTP boot clients.

### CODE REVIEW

**Comment by mmoll** [comment]
@lzap tests need updating

**Comment by lzap** [comment]
Can you teach me how to run tests locally? Tried to fix this and blindly force-pushing.

**Comment by mmoll** [comment]
@lzap Should be nothing more than:
```
bundle install
bundle exec rake
```

**Comment by mmoll** [comment]
merged, díky @lzap!

**Pull request merged**
