### PR TITLE
bump minor version and update changelog

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by domcleal** [comment]
:+1:

**Comment by ekohl** [comment]
Not sure if it needs to be a minor version since it's API compatible, but :+1: on green tests

**Comment by domcleal** [comment]
Minor version does mean that it's API compatible, but adding a new feature means a new minor when released.

**Comment by mmoll** [comment]
I was unsure, but a new parameter is new functionality, so minor, but personally I don't care :)

**Comment by mmoll** [comment]
:green_heart:

**Comment by ekohl** [comment]
semver.org doesn't explicitly say it, but I think minor versions for new functionality is better. Thanks!

**Pull request merged**
