### PR TITLE
Fixes #9321 - Do not add option domain if dhcp_use_option_domain is fals...

### PR DESCRIPTION
**Pull request by Moncky**
...e

### CODE REVIEW

**Comment by ekohl** [comment]
This lacks some code. Also, I'd prefer to avoid introducing new parameters. We could allow passing in an empty array for ```dnsdomain``` and only print the option when it is non-empty.

**Comment by Moncky** [comment]
Yeah the array had occurred to me, but I thought you would either want this enabled with $::domain or not at all.

I could change it to be the array, however I still think that you want a parameter so it can be over ridden as a smart class in the UI if you wish, (unless there is another way to add smart class options that I am unaware of)

**Comment by ekohl** [comment]
Since in the foreman installer modules the proxy is the one that calls the dhcp module, you could set an explicit parameter there. It keeps this module generic. Since I intend to merge puppetlabs/dhcp and theforeman/dhcp, I'd prefer to avoid additional parameters in this module.

**Comment by ekohl** [comment]
I didn't see you updated the PR, but I think it looks good now :+1:

**Comment by domcleal** [comment]
Merged, thanks @Moncky!

**Pull request closed without merging**
