### PR TITLE
Release 6.2.0

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Could you leave out changes to the existing releases? I suspect these are because of the concurrency (fixes are sadly unreleased in the gem).

**Comment by ehelms** [comment]
Updated with todays date

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Note we apply the `skip-changelog` label to release PRs. https://github.com/theforeman/foreman-installer-modulesync/commit/8e6476aa167900fb8e461a53943a23c56143bc04#diff-757da4b86492c64be1b8e5ea7c5cfbae717e2a555ab0746979b6164e5c6cb6a5 modified the script to do so. Maybe you forgot to git pull.

**Comment by ehelms** [comment]
I did not forget to git pull, that script just does not like to work for me.

**Comment by ekohl** [comment]
Any chance you have an old version of hub installed? I'm using the version that's in Fedora 33 and works for me.

**Comment by ekohl** [comment]
Btw, we can ignore CentOS 6 failures. It's just that the repos are no longer available. We can do a major version bump for it soon but IMHO it's not critical for branching to get it in.

**Pull request merged**
