### PR TITLE
Lease times

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by ekohl** [comment]
I don't mind being closer to the ISC-DHCP defaults so :+1: 

@domcleal I think we should document this in the release notes.

**Comment by domcleal** [comment]
Yeah, I don't mind either, but I wonder if they have been deliberately lowered so there are fewer old (unreleased) leases when doing provisioning or discovery?

**Comment by sathieu** [comment]
@domcleal I think there is adaptive-lease-time-threshold for this (see dhcpd.conf(5))

**Comment by sathieu** [comment]
Can I do something to help the merge of this patch?

**Comment by ekohl** [comment]
I think we can at least merge the first patch since that doesn't change the defaults. Maybe we can then look into why they've been lowered.

**Comment by mmoll** [comment]
I would be :+1: even with the changed defaults. The minor version of the module should maybe be bumped then.

**Comment by ekohl** [comment]
I can see that a low default lease time allows for fast renumbering, but I don't think that's a particularly interesting use case and most users would prefer stability over flexibility in their IP-addresses so I wouldn't mind changing the defaults either. @domcleal?

**Comment by domcleal** [comment]
@ekohl yep, fine by me!

**Comment by ekohl** [comment]
Thanks @sathieu!

**Pull request merged**
