### PR TITLE
Add dhcp::pools class to instantiate pools from Foreman

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by domcleal** [comment]
A related thought, but perhaps we could add a foreman() call in puppet-foreman_proxy to query Foreman for configured subnets and replicate the configuration into dhcpd.

https://github.com/theforeman/puppet-foreman/commit/6b9e2998dcfd643fd6fcb83ca746d6c3816e339f

**Comment by ekohl** [comment]
:+1: looks sane. Not sure about the foreman() call since the fields should match, but it's certainly something we can encourage users to do.

**Comment by ekohl** [comment]
What I mean by that is that first of all I'm not sure the fields match exactly and secondly that I don't know if we should include this by default. It can be documented though.

**Comment by domcleal** [comment]
Yeah, ignore that for now, I was just brainstorming.  I may look more into the subject in the future.

**Comment by ekohl** [comment]
I think @GregSutcliffe also mentioned the search does not return subnets but that was in the hallway at FOSDEM so I might mixing up something.

**Comment by bogdanr** [comment]
How about also allowing to specify the IP addresses for individual hosts?

**Comment by domcleal** [comment]
#55 replaces this I think, just without the defaults support.

**Pull request closed without merging**
